spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gsd
    password: password
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
      

server:
  port: 8080
  